spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resumedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: ramsharmaperfectmoker@gmail.com
    password: tvbyjmecmecsesvq
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        debug: true

gemini:
  api:
    key: ${GEMINI_API_KEY:AQ.Ab8RN6J4Q7Dnxh38O56EzxtMjtz84J77_RBAwhQDsEGZt5h_qw}

jwt:
  secret: ${JWT_SECRET:my-ultra-secure-and-extremely-long-secret-key-32-bytes-long-for-hmac-sha-256}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:rzp_test_SyBorAA0H8JUYz}
    secret: ${RAZORPAY_KEY_SECRET:LVwQcllozIOLJFLVDb7R3U1v}

logging:
  level:
    root: INFO
    com.resumebuilder.backend: DEBUG
